### ISSUE TITLE
Why XLA_PYTHON_CLIENT_MEM_FRACTION is set to "4.0" in run_docker.py

### ISSUE THREAD

**Issue by JasperW01** [google-deepmind/alphafold#832]
We are trying to run AlphaFold on new Nvidia generation GPUs, such as L4 & H100 and encountered some GPU memory issue which needs to check the setting of XLA_PYTHON_CLIENT_MEM_FRACTION. 

It looks like it's suggested to set it to "4.0" according to this code line: 
https://github.com/google-deepmind/alphafold/blob/7c9114c8423ac9db981d8365168464bab09b3e54/docker/run_docker.py#L250

However, it doesn't seem like consistent the elaborations about XLA_PYTHON_CLIENT_MEM_FRACTION in JAX [doc](https://jax.readthedocs.io/en/latest/gpu_memory_allocation.html), i.e. 

<img width="811" alt="image" src="https://github.com/google-deepmind/alphafold/assets/14971090/d1cfb7f7-1370-4d25-93a6-7c0e75390c02">

Appreciate your insight on this.

**Comment by Htomlinson14** [comment]
This allows device memory to spill to host memory, to allow larger folds. A fraction of 4, for example, will take up to 4X the device memory on the host and device combined (so 3X on the host). The host must have enough memory for this to work. When it spills to device memory there is a performance hit, but if there is enough memory the fold will succeed rather than OOMing.
